### ISSUE TITLE
How to change the clock colors?

### ISSUE THREAD

**Issue by Calistex** [jaeryo2357/circleTimer#3]
Hi there, thank you for this library.
I'd like to know if there's some kind of way to change the color of the text and lines around the clock, be it programmatically or by xml.
This is an example of what I mean: 

![photo_2023-01-15_20-19-56](https://user-images.githubusercontent.com/11682775/212562416-42f238a0-82b1-42b8-8b0e-d5449b43dde0.jpg)

**Comment by jaeryo2357** [comment]
Thanks! I'll take a look soon.

**Comment by Calistex** [comment]
Many thanks 😊

**Comment by jaeryo2357** [comment]
Sorry

You can use it in version 1.1.7
